// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgWmAJnCeHKyiDJGWIn1u-X2Sbut22XOw',
    appId: '1:90719446085:web:360b2f7d547c23e1746f2c',
    messagingSenderId: '90719446085',
    projectId: 'pokepedia-d135b',
    authDomain: 'pokepedia-d135b.firebaseapp.com',
    storageBucket: 'pokepedia-d135b.appspot.com',
    measurementId: 'G-9RJ8YVMZ8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_4wY__7AToZFZw8zj3kCoZOb48Xe58vM',
    appId: '1:90719446085:android:c546c28461cb9f63746f2c',
    messagingSenderId: '90719446085',
    projectId: 'pokepedia-d135b',
    storageBucket: 'pokepedia-d135b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS5K_ozEYwW-sWIeV9TjSsgV5aojoaDRw',
    appId: '1:90719446085:ios:b0be7cd8940000fe746f2c',
    messagingSenderId: '90719446085',
    projectId: 'pokepedia-d135b',
    storageBucket: 'pokepedia-d135b.appspot.com',
    iosBundleId: 'com.example.pokepedia1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS5K_ozEYwW-sWIeV9TjSsgV5aojoaDRw',
    appId: '1:90719446085:ios:eef6a10d282e2680746f2c',
    messagingSenderId: '90719446085',
    projectId: 'pokepedia-d135b',
    storageBucket: 'pokepedia-d135b.appspot.com',
    iosBundleId: 'com.example.pokepedia1.RunnerTests',
  );
}
